// packages/abuddy-sdk/src/fe/components/KeyboardShortcutInput.vue
<template>
  <div class="flex items-center gap-3" :class="containerClass">
    <div 
      class="relative flex-1 flex items-center px-3 py-2 bg-neutral-800 border rounded-lg text-sm cursor-pointer transition-all min-w-0"
      :class="[
        isRecording 
          ? 'border-blue-500/50 ring-2 ring-blue-500/20' 
          : 'border-neutral-700/50 hover:border-neutral-600',
        inputClass
      ]"
      :title="tooltipValue"
      @click="startRecording"
      tabindex="0"
      @focus="startRecording"
      @blur="stopRecording"
      @keydown.prevent="recordKeyPress"
    >
      <!-- Label on the left -->
      <span v-if="label" class="text-neutral-400 text-xs uppercase tracking-wider truncate mr-3 min-w-0">
        {{ label }}
      </span>
      
      <!-- Global badge if applicable -->
      <span 
        v-if="modelValue?.global && !isRecording"
        class="ml-auto mr-2 px-2 py-0.5 text-xs font-medium bg-blue-500/20 text-blue-400 rounded-md"
      >
        Global
      </span>
      
      <!-- Hotkey value on the right -->
      <span 
        class="font-mono flex-shrink-0 whitespace-nowrap"
        :class="[
          isRecording ? 'text-blue-400' : isEmpty ? 'text-neutral-500' : 'text-white',
          modelValue?.global && !isRecording ? '' : 'ml-auto'
        ]"
      >
        {{ displayValue }}
      </span>
      
      <!-- Keyboard icon -->
      <Keyboard 
        v-if="!isRecording && showIcon && isEmpty" 
        class="ml-2 w-4 h-4 text-neutral-500" 
      />
    </div>
    <button
      v-if="modelValue && showResetButton && !isEmpty"
      @click="resetShortcut"
      class="px-3 py-2 bg-neutral-800 border border-neutral-700/50 rounded-lg text-neutral-400 hover:text-neutral-300 hover:border-neutral-500 transition-all"
      :title="resetButtonTitle"
    >
      <Eraser class="w-4 h-4" />
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { Keyboard, Eraser } from 'lucide-vue-next'
import { useActorSystem } from '../composables/useActorSystem'

const actorSystem = useActorSystem()
import type { KeyboardShortcut } from '../../types'

interface Props {
  modelValue?: KeyboardShortcut | null
  id?: string
  label?: string
  placeholder?: string
  recordingPlaceholder?: string
  emptyText?: string
  showIcon?: boolean
  showResetButton?: boolean
  resetButtonTitle?: string
  containerClass?: string
  inputClass?: string
  multiArrowSupport?: boolean
  multiArrowTimeout?: number
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: 'Click to set shortcut',
  recordingPlaceholder: 'Press keys...',
  emptyText: 'Not set',
  showIcon: true,
  showResetButton: true,
  resetButtonTitle: 'Clear shortcut',
  containerClass: '',
  inputClass: '',
  multiArrowSupport: true,
  multiArrowTimeout: 500
})

const emit = defineEmits<{
  'update:modelValue': [value: KeyboardShortcut | null]
  'change': [value: KeyboardShortcut | null]
  'recording-start': []
  'recording-end': []
}>()

const isRecording = ref(false)
const pressedKeys = ref<Set<string>>(new Set())
let recordingTimeout: NodeJS.Timeout | null = null

// Check if shortcut is empty
const isEmpty = computed(() => {
  return !props.modelValue || !props.modelValue.key
})

// Format shortcut for display
const displayValue = computed(() => {
  if (isRecording.value) return props.recordingPlaceholder
  if (isEmpty.value) return props.emptyText
  
  const shortcut = props.modelValue!
  const parts = []
  
  // Add modifiers in consistent order
  if (shortcut.modifiers.includes('cmd')) parts.push('⌘')
  if (shortcut.modifiers.includes('ctrl')) parts.push('⌃')
  if (shortcut.modifiers.includes('option') || shortcut.modifiers.includes('alt')) parts.push('⌥')
  if (shortcut.modifiers.includes('shift')) parts.push('⇧')
  
  // Format the key
  const keyDisplay = formatKey(shortcut.key)
  if (keyDisplay) parts.push(keyDisplay)
  
  return parts.length > 0 ? parts.join(' ') : props.emptyText
})

// Format shortcut for tooltip (plain text)
const tooltipValue = computed(() => {
  if (isEmpty.value) return ''
  
  const shortcut = props.modelValue!
  const parts = []
  
  // Add modifiers in consistent order with plain text names
  if (shortcut.modifiers.includes('cmd')) parts.push('Command')
  if (shortcut.modifiers.includes('ctrl')) parts.push('Control')
  if (shortcut.modifiers.includes('option') || shortcut.modifiers.includes('alt')) parts.push('Option/Alt')
  if (shortcut.modifiers.includes('shift')) parts.push('Shift')
  
  // Format the key in plain text
  const keyDisplay = formatKeyPlainText(shortcut.key)
  if (keyDisplay) parts.push(keyDisplay)
  
  return parts.length > 0 ? parts.join(' + ') : ''
})

// Format key for plain text tooltip
const formatKeyPlainText = (key: string): string => {
  const keyMap: Record<string, string> = {
    'ArrowLeft': 'Left Arrow',
    'ArrowRight': 'Right Arrow',
    'ArrowUp': 'Up Arrow',
    'ArrowDown': 'Down Arrow',
    'Enter': 'Enter',
    'Tab': 'Tab',
    ' ': 'Space',
    'Escape': 'Escape',
    'Backspace': 'Backspace',
    'Delete': 'Delete',
    'PageUp': 'Page Up',
    'PageDown': 'Page Down',
    'Home': 'Home',
    'End': 'End',
  }
  
  // Handle combined arrow keys
  if (key.includes('+')) {
    const keys = key.split('+')
    const formattedKeys = keys.map(k => keyMap[k] || k.toUpperCase())
    return formattedKeys.join(' + ')
  }
  
  return keyMap[key] || key.toUpperCase()
}

// Format key for display
const formatKey = (key: string): string => {
  const keyMap: Record<string, string> = {
    'ArrowLeft': '←',
    'ArrowRight': '→',
    'ArrowUp': '↑',
    'ArrowDown': '↓',
    'Enter': '⏎',
    'Tab': '⇥',
    ' ': 'Space',
    'Escape': 'Esc',
    'Backspace': '⌫',
    'Delete': '⌦',
    'PageUp': 'PgUp',
    'PageDown': 'PgDn',
    'Home': 'Home',
    'End': 'End',
  }
  
  // Handle combined arrow keys (e.g., "ArrowUp+ArrowDown")
  if (key.includes('+')) {
    const keys = key.split('+')
    const formattedKeys = keys.map(k => keyMap[k] || k.toUpperCase())
    return formattedKeys.join(' ')
  }
  
  return keyMap[key] || key.toUpperCase()
}

// Start recording when input is focused
const startRecording = () => {
  isRecording.value = true
  pressedKeys.value.clear()
  // Notify application state to disable global hotkeys
  actorSystem.get('application')?.send({ type: 'HOTKEYS_RECORDING_START' })
  emit('recording-start')
}

// Stop recording when input loses focus
const stopRecording = () => {
  setTimeout(() => {
    isRecording.value = false
    pressedKeys.value.clear()
    if (recordingTimeout) {
      clearTimeout(recordingTimeout)
      recordingTimeout = null
    }
    // Re-enable global hotkeys
    actorSystem.get('application')?.send({ type: 'HOTKEYS_RECORDING_END' })
    emit('recording-end')
  }, 100)
}

// Record key press
const recordKeyPress = (event: KeyboardEvent) => {
  if (!isRecording.value) return
  
  // Collect modifiers
  const modifiers: string[] = []
  if (event.metaKey) modifiers.push('cmd')
  if (event.ctrlKey && !event.metaKey) modifiers.push('ctrl')
  if (event.altKey) modifiers.push('option')
  if (event.shiftKey) modifiers.push('shift')
  
  // Don't record modifier keys alone
  const isModifierKey = ['Meta', 'Control', 'Alt', 'Shift'].includes(event.key)
  if (isModifierKey) return
  
  // Handle arrow keys with multi-key support
  const isArrowKey = ['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(event.key)
  
  if (isArrowKey && props.multiArrowSupport) {
    // Add to pressed keys set
    pressedKeys.value.add(event.key)
    
    // Clear existing timeout
    if (recordingTimeout) clearTimeout(recordingTimeout)
    
    // Wait for more arrow keys
    recordingTimeout = setTimeout(() => {
      // Combine all arrow keys
      const arrowKeys = Array.from(pressedKeys.value).sort()
      const combinedKey = arrowKeys.length > 1 ? arrowKeys.join('+') : arrowKeys[0]
      
      // Emit the shortcut (preserve global flag if it exists)
      const shortcut: KeyboardShortcut = {
        modifiers,
        key: combinedKey,
        ...(props.modelValue?.global && { global: props.modelValue.global })
      }
      emit('update:modelValue', shortcut)
      emit('change', shortcut)
      
      // Stop recording
      pressedKeys.value.clear()
      isRecording.value = false
      
      // Re-enable global hotkeys since we're done
      actorSystem.get('application')?.send({ type: 'HOTKEYS_RECORDING_END' })
      emit('recording-end')
      
      ;(event.target as HTMLElement).blur()
    }, props.multiArrowTimeout)
  } else {
    // For non-arrow keys or when multi-arrow is disabled, save immediately
    const shortcut: KeyboardShortcut = {
      modifiers,
      key: event.key,
      ...(props.modelValue?.global && { global: props.modelValue.global })
    }
    emit('update:modelValue', shortcut)
    emit('change', shortcut)
    
    // Stop recording
    pressedKeys.value.clear()
    isRecording.value = false
    ;(event.target as HTMLElement).blur()
  }
}

// Reset shortcut
const resetShortcut = () => {
  emit('update:modelValue', null)
  emit('change', null)
}
</script>

// packages/video/src/agentbuddy-ui/settings/general/KeyboardShortcutInput.tsx
import {Icons} from '../../primitives/Icon';
import './KeyboardShortcutInput.module.css';
import {makeStyles} from '../../primitives/makeStyles';
const styles = makeStyles('KeyboardShortcutInput');

export type KeyboardShortcutValue =
  | string
  | {
      global?: boolean;
      key?: string;
      modifiers?: string[];
    }
  | null;

export function KeyboardShortcutInput({emptyText = 'Not set', label, value, showResetButton = true}: {
  emptyText?: string;
  label?: string;
  placeholder?: string;
  showResetButton?: boolean;
  value?: KeyboardShortcutValue;
}) {
  const displayValue = formatShortcut(value, emptyText);
  const tooltipValue = formatShortcutTooltip(value);
  const isEmpty = displayValue === emptyText;
  const isGlobal = typeof value === 'object' && value !== null && value.global === true;

  return (
    <div className={styles.root}>
      <span className={styles.box} title={tooltipValue}>
        {label ? <span className={styles.label}>{label}</span> : null}
        {isGlobal && !isEmpty ? <span className={styles.globalBadge}>Global</span> : null}
        {!isEmpty ? <span className={styles.key}>{displayValue}</span> : <span className={styles.empty}>{emptyText}</span>}
        {isEmpty ? <Icons.Keyboard className={styles.keyboardIcon} size={16} /> : null}
      </span>
      {!isEmpty && showResetButton ? (
        <button className={styles.resetButton} title="Clear shortcut" type="button">
          <Icons.Eraser size={16} />
        </button>
      ) : null}
    </div>
  );
}

function formatShortcut(value: KeyboardShortcutValue | undefined, emptyText: string) {
  if (!value) return emptyText;
  if (typeof value === 'string') return value;

  const parts = modifierParts(value.modifiers ?? []);
  const key = formatKey(value.key ?? '');
  if (key) parts.push(key);
  return parts.length > 0 ? parts.join(' ') : emptyText;
}

function formatShortcutTooltip(value: KeyboardShortcutValue | undefined) {
  if (!value) return '';
  if (typeof value === 'string') return value;

  const parts = plainModifierParts(value.modifiers ?? []);
  const key = formatKeyPlainText(value.key ?? '');
  if (key) parts.push(key);
  return parts.length > 0 ? parts.join(' + ') : '';
}

function modifierParts(modifiers: string[]) {
  const parts: string[] = [];
  if (modifiers.includes('cmd')) parts.push('⌘');
  if (modifiers.includes('ctrl')) parts.push('⌃');
  if (modifiers.includes('option') || modifiers.includes('alt')) parts.push('⌥');
  if (modifiers.includes('shift')) parts.push('⇧');
  return parts;
}

function plainModifierParts(modifiers: string[]) {
  const parts: string[] = [];
  if (modifiers.includes('cmd')) parts.push('Command');
  if (modifiers.includes('ctrl')) parts.push('Control');
  if (modifiers.includes('option') || modifiers.includes('alt')) parts.push('Option/Alt');
  if (modifiers.includes('shift')) parts.push('Shift');
  return parts;
}

function formatKey(key: string) {
  const keyMap: Record<string, string> = {
    ArrowDown: '↓',
    ArrowLeft: '←',
    ArrowRight: '→',
    ArrowUp: '↑',
    Backspace: '⌫',
    Delete: '⌦',
    End: 'End',
    Enter: '⏎',
    Escape: 'Esc',
    Home: 'Home',
    PageDown: 'PgDn',
    PageUp: 'PgUp',
    Tab: '⇥',
    ' ': 'Space',
  };

  if (key.includes('+')) {
    return key.split('+').map(part => keyMap[part] || part.toUpperCase()).join(' ');
  }

  return keyMap[key] || key.toUpperCase();
}

function formatKeyPlainText(key: string) {
  const keyMap: Record<string, string> = {
    ArrowDown: 'Down Arrow',
    ArrowLeft: 'Left Arrow',
    ArrowRight: 'Right Arrow',
    ArrowUp: 'Up Arrow',
    Backspace: 'Backspace',
    Delete: 'Delete',
    End: 'End',
    Enter: 'Enter',
    Escape: 'Escape',
    Home: 'Home',
    PageDown: 'Page Down',
    PageUp: 'Page Up',
    Tab: 'Tab',
    ' ': 'Space',
  };

  if (key.includes('+')) {
    return key.split('+').map(part => keyMap[part] || part.toUpperCase()).join(' + ');
  }

  return keyMap[key] || key.toUpperCase();
}
