// packages/video/src/agentbuddy-ui/database/QueryEditorHeader.tsx
import {Icons} from '../primitives/Icon';
import {cx} from '../primitives/classNames';
import {makeStyles} from '../primitives/makeStyles';
import type {DatabaseSurfaceState} from './databaseTypes';
import {KeyboardHint} from './KeyboardHint';
import {ModeTabs} from './ModeTabs';
import {QueryEditorActions} from './QueryEditorActions';
import {QueryEditorMessages} from './QueryEditorMessages';
import './QueryEditorHeader.module.css';

const styles = makeStyles('DatabaseQueryEditorHeader');

type QueryEditorHeaderProps = {
  state: Pick<DatabaseSurfaceState, 'activeMode' | 'currentQuery' | 'error' | 'executeQueryShortcut' | 'isAiPromptOpen' | 'isLoading' | 'mode' | 'successMessage'>;
};

export function QueryEditorHeader({state}: QueryEditorHeaderProps) {
  return (
    <div className={styles.root}>
      <div className={styles.left}>
        <ModeTabs activeMode={state.activeMode} />
        <div className={styles.divider} />
        <button className={styles.iconButton} title="Clear query" type="button">
          <Icons.FileX size={16} />
        </button>
        <button className={cx(styles.iconButton, state.isAiPromptOpen && styles.aiActive)} title="Generate query with AI" type="button">
          <Icons.Wand2 size={16} />
        </button>
        <KeyboardHint executeQuery={state.executeQueryShortcut} />
      </div>

      <div className={styles.right}>
        <QueryEditorMessages error={state.error} successMessage={state.successMessage} />
        <QueryEditorActions isDisabled={!state.currentQuery.trim()} isLoading={state.isLoading} mode={state.mode} />
      </div>
    </div>
  );
}

// packages/default-setup/src/features/database/fe/components/query-editor/QueryEditorHeader.vue
<template>
  <div class="@container flex items-center justify-between px-4 py-3 border-b border-neutral-800">
    <div class="flex items-center gap-1.5">
      <ModeTabs
        :active-mode="activeMode"
        @update:active-mode="$emit('update:activeMode', $event)"
      />

      <div class="w-px ml-1.5 h-5 bg-neutral-200 dark:bg-neutral-700"></div>

      <button
        @click="$emit('clear')"
        class="p-1.5 text-neutral-500 hover:text-neutral-300 dark:text-neutral-400 dark:hover:text-neutral-200 hover:bg-neutral-800 dark:hover:bg-neutral-700 rounded transition-colors"
        title="Clear query"
      >
        <FileX class="w-4 h-4" />
      </button>

      <button
        @click="$emit('ai-query')"
        :class="[
          'p-1.5 rounded transition-colors',
          isAiPromptOpen
            ? 'text-amber-400 bg-amber-500/15'
            : 'text-neutral-500 hover:text-neutral-300 dark:text-neutral-400 dark:hover:text-neutral-200 hover:bg-neutral-800 dark:hover:bg-neutral-700'
        ]"
        title="Generate query with AI"
      >
        <Wand2 class="w-4 h-4" />
      </button>
      <KeyboardHint :execute-query="executeQuery" />
    </div>

    <div class="flex items-center gap-2">
      <QueryEditorMessages
        :error="error"
        :success-message="successMessage"
      />


      <QueryEditorActions
        :is-loading="isLoading"
        :is-disabled="!currentQuery.trim()"
        :mode="mode"
        @execute="$emit('execute')"
        @toggle-mode="$emit('toggleMode')"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { FileX, Wand2 } from 'lucide-vue-next';
import ModeTabs from './ModeTabs.vue';
import KeyboardHint from './KeyboardHint.vue';
import QueryEditorMessages from './QueryEditorMessages.vue';
import QueryEditorActions from './QueryEditorActions.vue';

import type { KeyboardShortcut } from '@/registries/types';

defineProps<{
  activeMode: 'query' | 'examples';
  isLoading: boolean;
  currentQuery: string;
  error: string | null;
  successMessage: string;
  mode: 'query' | 'transaction';
  executeQuery?: KeyboardShortcut;
  isAiPromptOpen?: boolean;
}>();

defineEmits<{
  'update:activeMode': [mode: 'query' | 'examples'];
  execute: [];
  clear: [];
  'ai-query': [];
  toggleMode: [];
}>();
</script>
