// packages/renderer/src/plugins/code/features/pull-request/PRActionBar.vue
<template>
  <!-- Open PR actions -->
  <div v-if="pr && pr.state === 'OPEN'" class="flex items-center gap-1.5 px-3 py-2 border-t border-neutral-800 bg-neutral-800/30">
    <!-- Merge -->
    <div ref="mergeContainer" class="relative">
      <div class="flex">
        <button
          @click="$emit('merge', selectedMethod)"
          :disabled="!canMerge"
          :title="mergeTooltip"
          :class="MAIN_BTN_CLASSES[mergeVariant]"
          class="flex items-center gap-1 px-2 py-1 text-xs font-medium rounded-l transition-colors"
        >
          <Loader2 v-if="mergeVariant === 'merging' || mergeVariant === 'pending'" :size="11" class="animate-spin" />
          <AlertTriangle v-else-if="mergeVariant === 'error'" :size="11" />
          <Ban v-else-if="mergeVariant === 'blocked'" :size="11" />
          <GitMerge v-else :size="11" />
          <span>{{ mergeMethodList.find(m => m.value === selectedMethod)?.shortLabel }}</span>
        </button>
        <button
          @click="showMergeOptions = !showMergeOptions"
          :disabled="!canMerge"
          :title="mergeTooltip"
          :class="CHEVRON_BTN_CLASSES[mergeVariant]"
          class="px-1 py-1 rounded-r transition-colors"
        >
          <ChevronDown :size="11" />
        </button>
      </div>
      <!-- Merge method dropdown -->
      <div
        v-if="showMergeOptions"
        class="absolute bottom-full left-0 mb-1 rounded border border-neutral-700 bg-neutral-800 shadow-lg z-50 whitespace-nowrap"
      >
        <button
          v-for="method in mergeMethodList"
          :key="method.value"
          @click="selectMethod(method.value)"
          class="flex items-center w-full gap-2 px-3 py-1.5 text-xs text-left transition-colors hover:bg-neutral-700"
          :class="selectedMethod === method.value ? 'text-green-400' : 'text-neutral-300'"
        >
          <Check v-if="selectedMethod === method.value" :size="10" />
          <span v-else class="w-[10px]" />
          {{ method.label }}
        </button>
      </div>
    </div>

    <!-- Draft toggle -->
    <button
      @click="$emit('toggle-draft')"
      :disabled="isTogglingDraft"
      class="flex items-center gap-1 px-2 py-1 text-xs rounded transition-colors"
      :class="pr.isDraft
        ? 'bg-blue-700/50 text-blue-300 hover:bg-blue-700/70'
        : 'bg-neutral-700/50 text-neutral-400 hover:bg-neutral-700'"
      :title="pr.isDraft ? 'Mark as ready for review' : 'Convert to draft'"
    >
      <Loader2 v-if="isTogglingDraft" :size="11" class="animate-spin" />
      <FileEdit v-else :size="11" />
      <span>{{ pr.isDraft ? 'Ready' : 'Draft' }}</span>
    </button>

    <div class="flex-1" />

    <!-- Close -->
    <button
      @click="$emit('close')"
      :disabled="isClosing"
      class="flex items-center gap-1 px-2 py-1 text-xs rounded text-red-400 hover:bg-red-900/30 transition-colors disabled:opacity-50"
      title="Close pull request"
    >
      <Loader2 v-if="isClosing" :size="11" class="animate-spin" />
      <XCircle v-else :size="11" />
      <span>Close</span>
    </button>
  </div>

  <!-- Merged/Closed PR actions -->
  <div v-else-if="pr && (pr.state === 'MERGED' || pr.state === 'CLOSED')" class="flex items-center gap-1.5 px-3 py-2 border-t border-neutral-800 bg-neutral-800/30">
    <button
      @click="$emit('checkout-base')"
      class="flex items-center gap-1 px-2 py-1 text-xs rounded text-blue-400 hover:bg-blue-900/30 transition-colors"
      title="Checkout and pull base branch"
    >
      <GitBranch :size="11" />
      <span>Checkout & Pull Base</span>
    </button>
    <button
      @click="$emit('delete-branch')"
      :disabled="isDeletingBranch"
      class="flex items-center gap-1 px-2 py-1 text-xs rounded text-red-400 hover:bg-red-900/30 transition-colors disabled:opacity-50 ml-auto"
      title="Delete remote branch"
    >
      <Loader2 v-if="isDeletingBranch" :size="11" class="animate-spin" />
      <Trash2 v-else :size="11" />
      <span>Delete Branch</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, useTemplateRef } from 'vue'
import {
  GitMerge, GitBranch, ChevronDown, Check, XCircle, FileEdit, Loader2, Trash2,
  AlertTriangle, Ban,
} from 'lucide-vue-next'
import { useClickOutside } from '@/core/composables/useClickOutside'
import type { GhPullRequest } from '@app/api'

const props = defineProps<{
  pr: GhPullRequest | null
  isMerging: boolean
  isClosing: boolean
  isTogglingDraft: boolean
  isDeletingBranch: boolean
}>()

type StatusCheck = NonNullable<GhPullRequest['statusCheckRollup']>[number]
type MergeVariant = 'clean' | 'merging' | 'blocked' | 'error' | 'pending'

const FAILING_CONCLUSIONS = new Set(['FAILURE', 'CANCELLED', 'TIMED_OUT', 'ACTION_REQUIRED'])
const PENDING_STATUSES = new Set(['QUEUED', 'IN_PROGRESS', 'PENDING'])

const isFailing = (c: StatusCheck) =>
  (c.conclusion && FAILING_CONCLUSIONS.has(c.conclusion)) || c.state === 'FAILURE' || c.state === 'ERROR'

const isPending = (c: StatusCheck) =>
  (c.status && PENDING_STATUSES.has(c.status) && !c.conclusion) || (!c.status && c.state === 'PENDING')

/** Semantic state of the merge button: drives color, icon, tooltip, and disabled flag. */
const mergeState = computed<{ variant: MergeVariant; reason: string }>(() => {
  const pr = props.pr
  if (props.isMerging) return { variant: 'merging', reason: 'Merging…' }
  if (!pr)             return { variant: 'blocked', reason: 'No pull request selected' }
  if (pr.isDraft)      return { variant: 'blocked', reason: 'Cannot merge a draft PR' }

  if (pr.mergeable === 'CONFLICTING' || pr.mergeStateStatus === 'DIRTY')
    return { variant: 'error', reason: 'Cannot merge — branch has conflicts with base' }
  if (pr.mergeStateStatus === 'BEHIND')
    return { variant: 'blocked', reason: 'Branch is out of date with base — update it first' }
  if (pr.reviewDecision === 'CHANGES_REQUESTED')
    return { variant: 'error', reason: 'Cannot merge — changes have been requested' }
  if (pr.reviewDecision === 'REVIEW_REQUIRED')
    return { variant: 'blocked', reason: 'Cannot merge — required review is missing' }

  const checks = pr.statusCheckRollup ?? []
  if (checks.some(isFailing)) return { variant: 'error',   reason: 'Cannot merge — status checks are failing' }
  if (checks.some(isPending)) return { variant: 'pending', reason: 'Cannot merge — status checks are still running' }

  if (pr.mergeStateStatus === 'BLOCKED')
    return { variant: 'blocked', reason: 'Cannot merge — blocked by branch protection rules' }
  if (pr.mergeable === 'UNKNOWN' || pr.mergeStateStatus === 'UNKNOWN')
    return { variant: 'pending', reason: 'Checking mergeability…' }

  return { variant: 'clean', reason: 'Merge pull request' }
})

const canMerge = computed(() => mergeState.value.variant === 'clean')
const mergeTooltip = computed(() => mergeState.value.reason)
const mergeVariant = computed(() => mergeState.value.variant)

const MAIN_BTN_CLASSES: Record<MergeVariant, string> = {
  clean:   'bg-green-700/80 text-white hover:bg-green-600',
  merging: 'bg-green-700/60 text-white cursor-wait',
  blocked: 'bg-neutral-700/60 text-neutral-400 cursor-not-allowed',
  error:   'bg-red-950/50 text-red-300 border border-red-900/60 cursor-not-allowed',
  pending: 'bg-amber-950/50 text-amber-300 border border-amber-900/60 cursor-not-allowed',
}

const CHEVRON_BTN_CLASSES: Record<MergeVariant, string> = {
  clean:   'bg-green-700/80 text-white hover:bg-green-600 border-l border-green-600/50',
  merging: 'bg-green-700/60 text-white cursor-wait border-l border-green-600/50',
  blocked: 'bg-neutral-700/60 text-neutral-400 cursor-not-allowed border-l border-neutral-600/60',
  error:   'bg-red-950/50 text-red-300 cursor-not-allowed border-l border-red-900/60',
  pending: 'bg-amber-950/50 text-amber-300 cursor-not-allowed border-l border-amber-900/60',
}

defineEmits<{
  'merge': [method: 'merge' | 'squash' | 'rebase']
  'close': []
  'toggle-draft': []
  'delete-branch': []
  'checkout-base': []
}>()

const showMergeOptions = ref(false)
const selectedMethod = ref<'merge' | 'squash' | 'rebase'>('merge')
const mergeContainer = useTemplateRef<HTMLElement>('mergeContainer')

useClickOutside(mergeContainer, () => {
  showMergeOptions.value = false
})

const mergeMethodList = [
  { value: 'merge' as const, label: 'Create a merge commit', shortLabel: 'Merge' },
  { value: 'squash' as const, label: 'Squash and merge', shortLabel: 'Squash' },
  { value: 'rebase' as const, label: 'Rebase and merge', shortLabel: 'Rebase' },
]

const selectMethod = (method: 'merge' | 'squash' | 'rebase') => {
  selectedMethod.value = method
  showMergeOptions.value = false
}
</script>

// packages/video/src/agentbuddy-ui/code/PRActionBar.tsx
import {Icons} from '../primitives/Icon';
import {makeStyles} from '../primitives/makeStyles';
import type {PullRequestPanelState, PullRequestStatusCheckState} from './codeTypes';
import './PRActionBar.module.css';

const styles = makeStyles('PRActionBar');

export function PRActionBar({state}: {state: PullRequestPanelState}) {
  const pr = state.createdPr;
  if (pr && (pr.state === 'MERGED' || pr.state === 'CLOSED')) {
    return (
      <div className={styles.root}>
        <button className={styles.checkout} type="button"><Icons.GitBranch size={11} /><span>Checkout & Pull Base</span></button>
        <span className={styles.spacer} />
        <button className={styles.deleteBranch} type="button"><Icons.Trash2 size={11} /><span>Delete Branch</span></button>
      </div>
    );
  }

  const mergeVariant = getMergeVariant(state);
  const mergeText = mergeVariant === 'pending' ? 'Merge' : mergeVariant === 'merging' ? 'Merge' : 'Merge';
  return (
    <div className={styles.root}>
      <div className={styles.mergeGroup}>
        <button className={styles.merge} data-variant={mergeVariant} type="button">
          {mergeIcon(mergeVariant)}
          <span>{mergeText}</span>
        </button>
        <button className={styles.chevron} data-variant={mergeVariant} type="button"><Icons.ChevronDown size={11} /></button>
        {state.showMergeTooltip ? <MergeButtonTooltip state={state} variant={mergeVariant} /> : null}
      </div>
      <button className={pr?.isDraft ? styles.ready : styles.draft} type="button">
        <Icons.FileEdit size={11} />
        <span>{pr?.isDraft ? 'Ready' : 'Draft'}</span>
      </button>
      <span className={styles.spacer} />
      <button className={styles.close} type="button"><Icons.CircleX size={11} /><span>Close</span></button>
    </div>
  );
}

type MergeVariant = 'clean' | 'merging' | 'blocked' | 'error' | 'pending';

function getMergeVariant(state: PullRequestPanelState): MergeVariant {
  const pr = state.createdPr;
  if (!pr) return 'blocked';
  if (pr.isDraft) return 'blocked';
  if (pr.mergeable === 'CONFLICTING' || pr.mergeStateStatus === 'DIRTY') return 'error';
  if (pr.mergeStateStatus === 'BEHIND') return 'blocked';
  if (pr.reviewDecision === 'CHANGES_REQUESTED') return 'error';
  if (pr.reviewDecision === 'REVIEW_REQUIRED') return 'blocked';
  if (pr.statusCheckRollup?.some(isFailingCheck)) return 'error';
  if (pr.statusCheckRollup?.some(isPendingCheck)) return 'pending';
  if (pr.mergeStateStatus === 'BLOCKED') return 'blocked';
  if (pr.mergeable === 'UNKNOWN' || pr.mergeStateStatus === 'UNKNOWN') return 'pending';
  return 'clean';
}

function mergeIcon(variant: MergeVariant) {
  if (variant === 'pending' || variant === 'merging') return <Icons.Loader2 className={styles.spinner} size={11} />;
  if (variant === 'error') return <Icons.AlertTriangle size={11} />;
  if (variant === 'blocked') return <Icons.CircleX size={11} />;
  return <Icons.GitMerge size={11} />;
}

function MergeButtonTooltip({state, variant}: {state: PullRequestPanelState; variant: MergeVariant}) {
  const pr = state.createdPr;
  const relevantChecks = (pr?.statusCheckRollup ?? []).filter(variant === 'error' ? isFailingCheck : isPendingCheck);
  return (
    <div className={styles.tooltip}>
      <div className={styles.tooltipHeader}>
        {mergeIcon(variant)}
        <div>
          <strong>{tooltipTitle(state, variant)}</strong>
          <span>{tooltipDescription(state, variant)}</span>
        </div>
      </div>
      {relevantChecks.length ? (
        <div className={styles.checks}>
          {relevantChecks.slice(0, 5).map(check => (
            <div className={styles.checkRow} key={check.name}>
              {isPendingCheck(check) ? <Icons.Loader2 className={styles.spinner} size={10} /> : <Icons.CircleX size={10} />}
              <span>{check.name || 'Unnamed check'}</span>
              <em>{checkLabel(check)}</em>
            </div>
          ))}
        </div>
      ) : null}
      {variant === 'blocked' && pr?.isDraft ? <div className={styles.actionHint}>Click Ready to the right to mark as ready for review.</div> : null}
      {pr ? (
        <div className={styles.branchFooter}>
          <Icons.GitBranch size={10} />
          <span>{pr.headBranch ?? state.headBranch}</span>
          <Icons.ArrowRight size={10} />
          <span>{pr.baseBranch ?? state.baseBranch}</span>
        </div>
      ) : null}
    </div>
  );
}

function tooltipTitle(state: PullRequestPanelState, variant: MergeVariant) {
  const pr = state.createdPr;
  if (variant === 'clean') return 'Ready to merge';
  if (variant === 'merging') return 'Merging...';
  if (variant === 'pending') return pr?.mergeable === 'UNKNOWN' || pr?.mergeStateStatus === 'UNKNOWN' ? 'Checking mergeability' : 'Status checks running';
  if (variant === 'error') {
    if (pr?.mergeable === 'CONFLICTING' || pr?.mergeStateStatus === 'DIRTY') return 'Merge conflicts';
    if (pr?.reviewDecision === 'CHANGES_REQUESTED') return 'Changes requested';
    return 'Status checks failing';
  }
  if (!pr) return 'No pull request selected';
  if (pr.isDraft) return 'Draft pull request';
  if (pr.mergeStateStatus === 'BEHIND') return 'Branch is out of date';
  if (pr.reviewDecision === 'REVIEW_REQUIRED') return 'Required review missing';
  if (pr.mergeStateStatus === 'BLOCKED') return 'Blocked by branch protection';
  return 'Cannot merge';
}

function tooltipDescription(state: PullRequestPanelState, variant: MergeVariant) {
  const pr = state.createdPr;
  const base = pr?.baseBranch ?? state.baseBranch;
  if (variant === 'clean') return 'All checks passed and no blockers.';
  if (variant === 'merging') return 'Your merge is in progress.';
  if (variant === 'pending') return pr?.mergeable === 'UNKNOWN' || pr?.mergeStateStatus === 'UNKNOWN'
    ? 'GitHub is computing whether this PR can be merged. Try refreshing in a moment.'
    : 'Waiting for required status checks to complete.';
  if (variant === 'error') {
    if (pr?.mergeable === 'CONFLICTING' || pr?.mergeStateStatus === 'DIRTY') return `This branch has conflicts with ${base}. Resolve them locally and push.`;
    if (pr?.reviewDecision === 'CHANGES_REQUESTED') return 'A reviewer has requested changes. Address them before merging.';
    return 'One or more required status checks have failed.';
  }
  if (!pr) return 'Open a pull request for this branch to enable merging.';
  if (pr.isDraft) return 'Mark this PR as ready for review to enable merge.';
  if (pr.mergeStateStatus === 'BEHIND') return `Update this branch with the latest from ${base} before merging.`;
  if (pr.reviewDecision === 'REVIEW_REQUIRED') return 'This PR requires an approving review before it can be merged.';
  if (pr.mergeStateStatus === 'BLOCKED') return "This repository's branch protection rules are blocking the merge.";
  return 'This pull request cannot be merged right now.';
}

function isPendingCheck(check: PullRequestStatusCheckState) {
  return check.state === 'PENDING' || check.status === 'QUEUED' || check.status === 'IN_PROGRESS' || check.status === 'PENDING' || check.status === 'REQUESTED';
}

function isFailingCheck(check: PullRequestStatusCheckState) {
  return check.state === 'FAILURE' || check.state === 'ERROR' || check.conclusion === 'FAILURE' || check.conclusion === 'CANCELLED' || check.conclusion === 'TIMED_OUT';
}

function checkLabel(check: PullRequestStatusCheckState) {
  return (check.conclusion || check.status || check.state || '').toLowerCase().replace(/_/g, ' ');
}
