// apps/web/src/plugins/database/components/simple-table/components/ResultStates.vue
<template>
  <div v-if="state === 'loading'" class="flex items-center justify-center h-full">
    <div class="text-neutral-500">Loading...</div>
  </div>

  <div v-else-if="state === 'error'" class="flex items-center justify-center h-full p-4">
    <div class="text-center text-red-500">
      <div class="font-semibold">Query Error</div>
      <div class="mt-1 text-sm">{{ error }}</div>
    </div>
  </div>

  <div v-else-if="state === 'no-results'" class="flex items-center justify-center h-full">
    <div class="text-neutral-500">Execute a query to see results</div>
  </div>

  <div v-else-if="state === 'empty-array'" class="flex items-center justify-center h-full">
    <div class="text-neutral-500">Empty array returned</div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  state: 'loading' | 'error' | 'no-results' | 'empty-array';
  error?: string;
}

defineProps<Props>();
</script>

// packages/video/src/agentbuddy-ui/database/ResultStates.tsx
import {Icons} from '../primitives/Icon';
import {makeStyles} from '../primitives/makeStyles';
import './ResultStates.module.css';

const styles = makeStyles('DatabaseResultStates');

type ResultStatesProps = {
  error?: string | null;
  state: 'empty-array' | 'error' | 'loading' | 'no-results';
};

export function ResultStates({error, state}: ResultStatesProps) {
  if (state === 'loading') {
    return <div className={styles.center}><div className={styles.muted}>Loading...</div></div>;
  }
  if (state === 'error') {
    return (
      <div className={styles.center}>
        <div className={styles.error}>
          <div>Query Error</div>
          <p>{error}</p>
        </div>
      </div>
    );
  }
  if (state === 'empty-array') {
    return <div className={styles.center}><div className={styles.muted}>Empty array returned</div></div>;
  }
  return (
    <div className={styles.center}>
      <div className={styles.noResults}>
        <Icons.Database size={64} />
        <p>Execute a query to see the results</p>
      </div>
    </div>
  );
}
