// src/core/Toolbar.vue
<template>
  <div class="flex flex-col w-16 h-full py-4 text-white bg-primary-800">
    <div class="flex flex-col items-center space-y-6">
      <button
        v-for="item in toolbarItems"
        :key="item.id"
        :class="[
          'p-2 rounded-lg transition-all duration-200 ease-in-out',
          activeItem === item.id
            ? 'bg-primary-600 text-white'
            : 'text-neutral-400 hover:text-white hover:bg-primary-700'
        ]"
        @click="$emit('select-item', item.id)"
        :title="item.label"
      >
        <component :is="item.icon" :size="24" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { 
  LayoutGrid, 
  Code, 
  Box, 
  Folder, 
  ChevronRight, 
  Star, 
  BarChart2, 
  Settings
} from 'lucide-vue-next'

interface ToolbarProps {
  activeItem: string
}

defineProps<ToolbarProps>()
defineEmits<(e: 'select-item', item: string) => void>()

const toolbarItems = [
  { id: 'dashboard', icon: LayoutGrid, label: 'Dashboard' },
  { id: 'code', icon: Code, label: 'Code' },
  { id: 'components', icon: Box, label: 'Components' },
  { id: 'files', icon: Folder, label: 'Files' },
  { id: 'terminal', icon: ChevronRight, label: 'Terminal' },
  { id: 'favorites', icon: Star, label: 'Favorites' },
  { id: 'analytics', icon: BarChart2, label: 'Analytics' },
  { id: 'settings', icon: Settings, label: 'Settings' },
]
</script>

<style scoped>
/* Add any component-specific styles here */
</style>

// src/components/Toolbar.tsx
import React from 'react';
import { 
  LayoutGrid, 
  Code, 
  Box, 
  Folder, 
  ChevronRight, 
  Star, 
  BarChart2, 
  Settings
} from 'lucide-react';

interface ToolbarProps {
  activeItem: string;
  onSelectItem: (item: string) => void;
}

const Toolbar: React.FC<ToolbarProps> = ({ activeItem, onSelectItem }) => {
  const toolbarItems = [
    { id: 'dashboard', icon: <LayoutGrid size={24} />, label: 'Dashboard' },
    { id: 'code', icon: <Code size={24} />, label: 'Code' },
    { id: 'components', icon: <Box size={24} />, label: 'Components' },
    { id: 'files', icon: <Folder size={24} />, label: 'Files' },
    { id: 'terminal', icon: <ChevronRight size={24} />, label: 'Terminal' },
    { id: 'favorites', icon: <Star size={24} />, label: 'Favorites' },
    { id: 'analytics', icon: <BarChart2 size={24} />, label: 'Analytics' },
    { id: 'settings', icon: <Settings size={24} />, label: 'Settings' },
  ];

  return (
    <div className="flex flex-col h-full bg-primary-800 text-white py-4 w-16">
      <div className="flex flex-col items-center space-y-6">
        {toolbarItems.map((item) => (
          <button
            key={item.id}
            className={`p-2 rounded-lg transition-all duration-200 ease-in-out ${
              activeItem === item.id
                ? 'bg-primary-600 text-white'
                : 'text-neutral-400 hover:text-white hover:bg-primary-700'
            }`}
            onClick={() => onSelectItem(item.id)}
            title={item.label}
          >
            {item.icon}
          </button>
        ))}
      </div>
    </div>
  );
};

export default Toolbar;
