// packages/video/src/agentbuddy-ui/database/ResultsInfoBar.tsx
import {makeStyles} from '../primitives/makeStyles';
import {Icons} from '../primitives/Icon';
import './ResultsInfoBar.module.css';

const styles = makeStyles('DatabaseResultsInfoBar');

type ResultsInfoBarProps = {
  executionTime: number | null;
  resultCount: number;
  resultType: 'array' | 'object' | 'primitive';
  hasResult: boolean;
};

export function ResultsInfoBar({executionTime, hasResult, resultCount, resultType}: ResultsInfoBarProps) {
  return (
    <div className={styles.root}>
      <div className={styles.inner}>
        <div className={styles.left}>
          <div className={styles.count}>
            {!hasResult ? (
              <>
                <Icons.List size={14} />
                <span>No results</span>
              </>
            ) : resultType === 'array' ? (
              <>
                <strong>{resultCount.toLocaleString()}</strong>
                <span>{resultCount === 1 ? 'result' : 'results'}</span>
              </>
            ) : (
              <span>{resultType === 'object' ? 'Object result' : 'Primitive value'}</span>
            )}
          </div>
          {hasResult ? (
            <div className={styles.type}>
              <Icons.Code size={12} />
              {resultType}
            </div>
          ) : null}
        </div>
        {executionTime !== null ? (
          <div className={styles.time}>
            <Icons.Clock size={14} />
            <span>{formatExecutionTime(executionTime)}</span>
          </div>
        ) : null}
      </div>
    </div>
  );
}

function formatExecutionTime(time: number) {
  if (time < 1) return `${time.toFixed(3)}ms`;
  if (time < 1000) return `${time.toFixed(2)}ms`;
  return `${(time / 1000).toFixed(3)}s`;
}

// apps/web/src/plugins/database/components/simple-table/components/ResultsInfoBar.vue
<template>
  <div class="px-4 py-2 bg-gray-50 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
    <div class="flex items-center justify-between">
      <div class="text-sm text-gray-600 dark:text-gray-400">
        <template v-if="!queryResult">
          No results
        </template>
        <template v-else-if="resultType === 'array'">
          {{ resultCount }} {{ resultCount === 1 ? 'result' : 'results' }}
        </template>
        <template v-else-if="resultType === 'object'">
          Object result
        </template>
        <template v-else-if="resultType === 'primitive'">
          Primitive value
        </template>
      </div>
      <div class="flex items-center gap-4 text-xs text-gray-500">
        <span v-if="executionTime !== null" class="text-gray-500 dark:text-gray-400">
          Executed in {{ formatExecutionTime(executionTime) }}
        </span>
        <span v-if="queryResult">
          {{ resultType }}{{ isArrayOfPrimitives ? ' (primitives)' : '' }}
        </span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ResultType } from '../composables/useResultAnalysis';

interface Props {
  queryResult: any;
  resultType: ResultType;
  resultCount: number;
  isArrayOfPrimitives: boolean;
  executionTime: number | null;
}

defineProps<Props>();

function formatExecutionTime(time: number): string {
  if (time < 1) {
    return `${time.toFixed(3)}ms`;
  } else if (time < 1000) {
    return `${time.toFixed(2)}ms`;
  }
  return `${(time / 1000).toFixed(3)}s`;
}
</script>
