// src/components/ContextItem.tsx
import React, { useState } from 'react';
import { ContextItem as ContextItemType } from '../types';
import { ChevronDown, ChevronUp, Copy } from 'lucide-react';

interface ContextItemProps {
  item: ContextItemType;
}

const ContextItem: React.FC<ContextItemProps> = ({ item }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  const toggleExpand = () => {
    setIsExpanded(!isExpanded);
  };

  return (
    <div className="mb-3 bg-white rounded-lg shadow-sm border border-neutral-200 overflow-hidden">
      <div 
        className="px-4 py-3 flex items-center justify-between cursor-pointer"
        onClick={toggleExpand}
      >
        <h3 className="font-medium text-sm">{item.title}</h3>
        <button className="text-neutral-500">
          {isExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </button>
      </div>
      
      {isExpanded && (
        <div className="p-4 border-t border-neutral-200 animate-slide-down">
          {item.type === 'code' ? (
            <div className="relative">
              <pre className="bg-neutral-900 text-white p-3 rounded text-xs font-mono overflow-x-auto">
                <code>{item.content}</code>
              </pre>
              <button 
                className="absolute top-2 right-2 p-1 bg-neutral-800 hover:bg-neutral-700 rounded text-neutral-400 hover:text-white transition-colors"
                title="Copy to clipboard"
              >
                <Copy size={14} />
              </button>
            </div>
          ) : (
            <p className="text-sm text-neutral-700">{item.content}</p>
          )}
        </div>
      )}
    </div>
  );
};

export default ContextItem;

// src/core/ContextItem.vue
<template>
  <div class="mb-3 overflow-hidden border rounded-lg shadow-sm bg-neutral-800 border-neutral-700">
    <div 
      class="flex items-center justify-between px-4 py-3 cursor-pointer"
      @click="isExpanded = !isExpanded"
    >
      <h3 class="text-sm font-medium">{{ item.title }}</h3>
      <button class="text-neutral-500">
        <component :is="isExpanded ? ChevronUp : ChevronDown" :size="16" />
      </button>
    </div>
    
    <div v-if="isExpanded" class="p-4 border-t border-neutral-700 animate-slide-down">
      <template v-if="item.type === 'code'">
        <div class="relative">
          <pre class="p-3 overflow-x-auto font-mono text-xs text-white rounded bg-neutral-900">
            <code>{{ item.content }}</code>
          </pre>
          <button 
            class="absolute p-1 transition-colors rounded top-2 right-2 bg-neutral-800 hover:bg-neutral-700 text-neutral-400 hover:text-white"
            title="Copy to clipboard"
          >
            <Copy :size="14" />
          </button>
        </div>
      </template>
      
      <template v-else>
        <p class="text-sm text-neutral-200">{{ item.content }}</p>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { ChevronDown, ChevronUp, Copy } from 'lucide-vue-next'
import type { ContextItem as ContextItemType } from './types'

interface ContextItemProps {
  item: ContextItemType
}

defineProps<ContextItemProps>()

const isExpanded = ref(false)
</script>

<style scoped>
/* Add any component-specific styles here */
</style>
